apiVersion: v1
kind: Service
metadata:
  name: gitops-service
  namespace: gitops
spec:
  type: NodePort
  selector:
    app: gitops-engine
  ports:
    - port: 80
      targetPort: 8084
      nodePort: 30007